on:
  schedule:
    - cron: '0 0 * * 0' # Run weekly on Sundays
  repository_dispatch: # Run manually
    types: [check-links]

name: Check Links
jobs:
  check:
    name: Check Links
    runs-on: ubuntu-latest
    steps:
      - name: Check Links
        uses: technote-space/broken-link-checker-action@v2
        with:
          TARGET: https://vaadin.com/docs-beta/latest/
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
